// Generated by CoffeeScript 1.8.0
var Background, Ball, game;

Background = function() {};

Background.prototype.draw = function(context) {
  context.fillStyle = "#000";
  context.fillRect(0, 0, game.width, game.height);
};

Ball = function() {
  Entity.call(this);
  this.width = 20;
  this.height = 20;
  this.x = game.width / 2 - this.width;
  this.y = game.height / 2 - this.height;
  this.yVelocity = 5;
};

Ball.prototype = Object.create(Entity.prototype);

Ball.prototype.constructor = Ball;

Ball.prototype.update = function() {
  Entity.prototype.update.apply(this, arguments);
  if (this.y > game.height - this.height || this.y < 0) {
    this.yVelocity *= -1;
  }
};

game = new Game($('canvas')[0]);

game.entities = [new Background(), new Ball()];

game.start();

$('canvas')[0].focus();
