// Generated by CoffeeScript 1.8.0
var Game;

Game = function(canvas) {
  var self;
  self = this;
  this.context = canvas.getContext("2d");
  this.width = canvas.width;
  this.height = canvas.height;
  this.keyPressed = {};
  $("canvas").on("keydown keyup", function(e) {
    var keyName;
    keyName = Game.keys[e.which];
    if (keyName) {
      this.keyPressed[keyName] = e.type === "keydown";
      e.preventDefault();
    }
  });
};

Game.keys = {
  32: "space",
  37: "left",
  38: "up",
  39: "right",
  40: "down"
};

Game.prototype.start = function() {
  var fps, interval, self;
  self = this;
  fps = 60;
  interval = fps / 1000;
  setInterval((function() {
    self.update();
    self.draw();
  }), interval);
};

Game.prototype.update = function() {
  this.entities.forEach(function(entity) {
    if (entity.update) {
      entity.update();
    }
  });
};

Game.prototype.draw = function() {
  var self;
  self = this;
  this.entities.forEach(function(entity) {
    if (entity.draw) {
      entity.draw(this.context);
    }
  });
};
